import { ArrowRight, CheckCircle2, Layers3 } from 'lucide-react'
import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import type { User } from '../api/types'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'

function AuthLayout({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <div className="auth-shell"><section className="auth-brand-panel"><div className="brand hero-brand"><span className="brand-mark">F</span><span>FlowDeck</span></div><div><span className="eyebrow">Plan together</span><h1>Move work<br/><em>forward.</em></h1><p>Projects, boards, priorities, checklists and team ownership in one focused workspace.</p></div><div className="auth-feature"><Layers3 size={22}/><span>Built around a permission-safe Django API and a fast Kanban workflow.</span></div></section><section className="auth-form-panel"><div className="auth-card"><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></div>
}

export function LoginPage() {
  const { user, login } = useAuth(); const toast = useToast(); const navigate = useNavigate()
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  if (user) return <Navigate to="/" replace />
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await login(email,password); toast('Welcome back.','success'); navigate('/') } catch(e) { setError(e instanceof Error ? e.message : 'Could not log in.') } finally { setBusy(false) } }
  return <AuthLayout title="Welcome back" subtitle="Sign in to your FlowDeck workspace."><form className="stack-form" onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error && <div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Signing in…':<>Sign in <ArrowRight size={17}/></>}</button></form><div className="auth-links"><Link to="/forgot-password">Forgot password?</Link><span>New to FlowDeck? <Link to="/register">Create account</Link></span></div></AuthLayout>
}

export function RegisterPage() {
  const navigate=useNavigate(); const toast=useToast(); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({display_name:'',email:'',password:'',password_confirm:''})
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.post<User>('/auth/register/',form);toast('Account created. Check your email for the verification link.','success');navigate('/login')}catch(e){setError(e instanceof Error?e.message:'Could not register.')}finally{setBusy(false)}}
  return <AuthLayout title="Create your account" subtitle="Start with a workspace, then turn work into visible progress."><form className="stack-form" onSubmit={submit}><label>Display name<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required minLength={10}/></label><label>Confirm password<input type="password" value={form.password_confirm} onChange={e=>setForm({...form,password_confirm:e.target.value})} required minLength={10}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Creating…':<>Create account <ArrowRight size={17}/></>}</button></form><div className="auth-links"><span>Already have an account? <Link to="/login">Sign in</Link></span></div></AuthLayout>
}

export function VerifyEmailPage(){const [params]=useSearchParams();const navigate=useNavigate();const [state,setState]=useState<'busy'|'ok'|'error'>('busy');const [message,setMessage]=useState('Verifying your email…');useEffect(()=>{void api.post('/auth/verify-email/',{uid:params.get('uid'),token:params.get('token')}).then(()=>{setState('ok');setMessage('Email verified. You can now use FlowDeck.')}).catch(e=>{setState('error');setMessage(e instanceof Error?e.message:'Verification failed.')})},[params]);return <AuthLayout title="Email verification" subtitle="One quick security step before collaboration features unlock."><div className={`status-card ${state}`}>{state==='ok'?<CheckCircle2 size={38}/>:<div className={state==='busy'?'spinner':''}/>}<strong>{message}</strong>{state!=='busy'&&<button className="primary-button" onClick={()=>navigate('/login')}>Continue to login</button>}</div></AuthLayout>}

export function ForgotPasswordPage(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api.post('/auth/password/forgot/',{email});setSent(true)}finally{setBusy(false)}}return <AuthLayout title="Reset your password" subtitle="We'll send a reset link if the account exists.">{sent?<div className="status-card ok"><CheckCircle2 size={38}/><strong>Check your email for the reset link.</strong><Link to="/login">Back to login</Link></div>:<form className="stack-form" onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button className="primary-button" disabled={busy}>{busy?'Sending…':'Send reset link'}</button></form>}</AuthLayout>}

export function ResetPasswordPage(){const[params]=useSearchParams();const navigate=useNavigate();const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.post('/auth/password/reset/',{uid:params.get('uid'),token:params.get('token'),new_password:password,new_password_confirm:confirm});navigate('/login')}catch(e){setError(e instanceof ApiError?e.message:'Could not reset password.')}finally{setBusy(false)}}return <AuthLayout title="Choose a new password" subtitle="Use at least 10 characters and avoid common passwords."><form className="stack-form" onSubmit={submit}><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={10}/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={10}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Saving…':'Reset password'}</button></form></AuthLayout>}
