import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, Boxes, Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import type { Paginated, Workspace } from '../api/types'
import { Modal } from '../components/Modal'
import { useToast } from '../context/ToastContext'

export function WorkspacesPage(){const qc=useQueryClient();const toast=useToast();const[open,setOpen]=useState(false);const[name,setName]=useState('');const[description,setDescription]=useState('');const query=useQuery({queryKey:['workspaces'],queryFn:()=>api.get<Paginated<Workspace>>('/workspaces/?limit=100')});const create=useMutation({mutationFn:()=>api.post<Workspace>('/workspaces/',{name,description}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['workspaces']});setOpen(false);setName('');setDescription('');toast('Workspace created.','success')},onError:e=>toast(e.message,'error')});function submit(e:FormEvent){e.preventDefault();create.mutate()}return <div className="page"><div className="page-heading"><div><span className="eyebrow">Workspaces</span><h1>Your teams and projects.</h1><p>Separate work cleanly, keep roles clear, and invite the right people.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/> Create workspace</button></div>{query.isLoading?<div className="screen-loader"><div className="spinner"/>Loading workspaces…</div>:query.data?.results.length?<div className="workspace-grid">{query.data.results.map(w=><Link className="workspace-card" key={w.id} to={`/workspaces/${w.id}`}><div className="workspace-card-top"><div className="workspace-icon"><Boxes size={21}/></div><span className="role-pill">{w.my_role}</span></div><h2>{w.name}</h2><p>{w.description||'No description yet.'}</p><div className="workspace-card-foot"><span>{w.slug}</span><ArrowRight size={17}/></div></Link>)}</div>:<div className="empty-state large"><Boxes size={40}/><h2>Create your first workspace</h2><p>A workspace holds your team, projects and boards.</p><button className="primary-button" onClick={()=>setOpen(true)}>Create workspace</button></div>}{open&&<Modal title="Create workspace" onClose={()=>setOpen(false)}><form className="stack-form" onSubmit={submit}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required autoFocus/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button" disabled={create.isPending}>{create.isPending?'Creating…':'Create workspace'}</button></div></form></Modal>}</div>}
